.\" Process this file with
.\" groff -man -Tascii hpc-clust.1
.\"
.TH MAPSEQ 1 "APR 2017" Linux "User Manuals"
.SH NAME
MAPseq: improving speed, accuracy and consistency in metagenomic ribosomal RNA analysis
.SH SYNOPSIS
.B mapseq [-nthreads <count>] <input.fa> <database.fa> <database.tax> [database.tax2 database.tax3 ...]
.P
.SH DESCRIPTION
.B MAPseq
is a set of fast and accurate sequence read classification tools designed to classify ribosomal
RNA sequences in terms of their taxonomy and OTU classification. This is done by using a
reference set of full-length ribosomal RNA sequences
.I database.fa
for which taxonomies
.I database.tax
are known, and for which a set of high quality OTU clusters has been previously generated.
For each read, the best guess and correspoding confidence in the assignment is shown at
each taxonomic and OTU level.

.SH OPTIONS
.IP -nthreads
Number of threads to run per node
.IP -tophits
Number of best matches to keep for full alignment
.IP -topotus
Number of sequence cluster representatives to use from which to recruit the top hits for full alignment

.SH AUTHORS
Joao F. Matias Rodrigues <joao.rodrigues@imls.uzh.ch>
.P
Thomas B. S. Schmidt <sebastian.schmidt@imls.uzh.ch>
.P
Janko Tackmann <janko.tackmann@imls.uzh.ch>
.P
Christian von Mering <mering@imls.uzh.ch>

